import {
  Student,
  Parent,
  Teacher,
  SchoolClass,
  Subject,
  AttendanceRecord,
  NotificationItem,
  EmergencyContact,
  HomeworkItem,
  MarkItem,
  RAGDocument,
  DocumentChunk,
  MCQQuestion,
  Flashcard,
  StudentAlert,
  UserAccount,
  RBACRolePermissions,
  AcademicEvent,
  TimetableSlot,
  AuditLogEntry,
  TeacherCompliance,
  StudyMaterial,

  StudentProgressNote,
  ParentMessage,
  PastExamPaper,
  RevisionChecklistItem,
  TimedPracticeQuestion,
} from "./types";



export const INITIAL_CLASSES: SchoolClass[] = [
  { id: "c-10a", name: "Grade 10 - Lily", gradeLevel: 10, section: "A", roomNumber: "Lab 3", studentCount: 28, capacity: 30, classTeacher: "Dr. Amina Qureshi" },
  { id: "c-10b", name: "Grade 10 - Jasmine", gradeLevel: 10, section: "B", roomNumber: "Hall 2", studentCount: 26, capacity: 30, classTeacher: "Ms. Hiba Rashid" },
  { id: "c-9a", name: "Grade 9 - Rose", gradeLevel: 9, section: "A", roomNumber: "Room 101", studentCount: 30, capacity: 32, classTeacher: "Mrs. Sarah Jenkins" },
  { id: "c-8a", name: "Grade 8 - Daisy", gradeLevel: 8, section: "A", roomNumber: "Room 204", studentCount: 25, capacity: 30, classTeacher: "Engr. Noor Fatima" },
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: "sub-1", name: "Biology & Life Sciences", code: "BIO-101", classId: "c-10a", teacherName: "Dr. Amina Qureshi", periodsPerWeek: 5 },
  { id: "sub-2", name: "Mathematics & Algebra", code: "MTH-102", classId: "c-10a", teacherName: "Ms. Hiba Rashid", periodsPerWeek: 5 },
  { id: "sub-3", name: "English Literature", code: "ENG-103", classId: "c-10a", teacherName: "Mrs. Sarah Jenkins", periodsPerWeek: 4 },
  { id: "sub-4", name: "Computer Science & AI", code: "CS-104", classId: "c-10a", teacherName: "Engr. Noor Fatima", periodsPerWeek: 4 },
  { id: "sub-5", name: "Physics", code: "PHY-105", classId: "c-10a", teacherName: "Dr. Samira Al-Mansoor", periodsPerWeek: 4 },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stu-1",
    userId: "u-stu-1",
    fullName: "Sara Ahmed",
    rollNumber: "SAF-2026-042",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-1",
    parentName: "Tariq Ahmed",
    parentPhone: "+1 (555) 349-2810",
    parentEmail: "tariq.ahmed@example.com",
    bloodGroup: "O+",
    rfidCardId: "RFID-99482",
    qrCodeToken: "QR-SARA-AHMED-10A-99482",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:45 AM",
    attendanceRate: 98.4,
  },
  {
    id: "stu-2",
    userId: "u-stu-2",
    fullName: "Ayesha Khan",
    rollNumber: "SAF-2026-043",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-2",
    parentName: "Yasmin Khan",
    parentPhone: "+1 (555) 782-9011",
    parentEmail: "yasmin.khan@example.com",
    bloodGroup: "A+",
    rfidCardId: "RFID-99483",
    qrCodeToken: "QR-AYESHA-KHAN-10A-99483",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:52 AM",
    attendanceRate: 96.0,
  },
  {
    id: "stu-3",
    userId: "u-stu-3",
    fullName: "Fatima Noor",
    rollNumber: "SAF-2026-044",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-3",
    parentName: "Bilal Noor",
    parentPhone: "+1 (555) 438-1192",
    parentEmail: "bilal.noor@example.com",
    bloodGroup: "B+",
    rfidCardId: "RFID-99484",
    qrCodeToken: "QR-FATIMA-NOOR-10A-99484",
    photoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: false,
    lastSafetyCheckin: "Yesterday at 01:45 PM",
    attendanceRate: 94.2,
  },
  {
    id: "stu-4",
    userId: "u-stu-4",
    fullName: "Zainab Malik",
    rollNumber: "SAF-2026-045",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-4",
    parentName: "Farah Malik",
    parentPhone: "+1 (555) 902-3341",
    parentEmail: "farah.malik@example.com",
    bloodGroup: "AB+",
    rfidCardId: "RFID-99485",
    qrCodeToken: "QR-ZAINAB-MALIK-10A-99485",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:40 AM",
    attendanceRate: 99.1,
  },
  {
    id: "stu-5",
    userId: "u-stu-5",
    fullName: "Zainab Ahmed",
    rollNumber: "SAF-2026-088",
    classId: "c-8a",
    className: "Grade 8 - Daisy",
    parentId: "par-1",
    parentName: "Tariq Ahmed",
    parentPhone: "+1 (555) 349-2810",
    parentEmail: "tariq.ahmed@example.com",
    bloodGroup: "O+",
    rfidCardId: "RFID-99486",
    qrCodeToken: "QR-ZAINAB-AHMED-8A-99486",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:42 AM",
    attendanceRate: 97.2,
  },
];

export const INITIAL_PARENTS: Parent[] = [
  {
    id: "par-1",
    userId: "u-par-1",
    fullName: "Tariq Ahmed",
    relationship: "Father",
    studentIds: ["stu-1", "stu-5"],
    studentNames: ["Sara Ahmed", "Zainab Ahmed"],
    emergencyPhone: "+1 (555) 349-2810",
    whatsappEnabled: true,
    address: "742 Evergreen Terrace, Sector F-8",
  },
];


export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: "tea-1",
    userId: "u-tea-1",
    fullName: "Dr. Amina Qureshi",
    employeeId: "TEA-882",
    department: "Science & Biology",
    qualification: "Ph.D. in Cellular Biology",
    assignedClasses: ["Grade 10 - Lily", "Grade 9 - Rose"],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    rollNumber: "SAF-2026-042",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "07:45 AM",
    method: "qr_scan",
    status: "present",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-2",
    studentId: "stu-2",
    studentName: "Ayesha Khan",
    rollNumber: "SAF-2026-043",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "07:52 AM",
    method: "rfid_tap",
    status: "present",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-3",
    studentId: "stu-3",
    studentName: "Fatima Noor",
    rollNumber: "SAF-2026-044",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    method: "manual",
    status: "absent",
    parentNotifiedArrival: false,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-4",
    studentId: "stu-4",
    studentName: "Zainab Malik",
    rollNumber: "SAF-2026-045",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "08:15 AM",
    method: "qr_scan",
    status: "late",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-5",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    rollNumber: "SAF-2026-088",
    className: "Grade 8 - Daisy",
    date: new Date().toISOString().split("T")[0],
    checkIn: "07:42 AM",
    method: "rfid_tap",
    status: "present",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
];


export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "attendance",
    title: "Safe Arrival Confirmed",
    message: "Your daughter Sara Ahmed safely reached school at 7:45 AM via North Gate Smart QR Entry.",
    read: false,
    channel: "whatsapp",
    createdAt: "10 mins ago",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-2",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "homework",
    title: "Biology Homework Assigned",
    message: "Chapter 5: Photosynthesis & Cellular Respiration worksheet is due tomorrow by 4:00 PM.",
    read: false,
    channel: "app",
    createdAt: "1 hour ago",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-3",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "marks",
    title: "Monthly Quiz Marks Published",
    message: "Sara scored 48/50 (Grade: A+) in Mathematics Quadratic Equations test.",
    read: true,
    channel: "email",
    createdAt: "Yesterday",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-4",
    recipientId: "u-all",
    recipientRole: "parent",
    category: "announcements",
    title: "Annual Girls STEM & Robotics Fair",
    message: "Parents are warmly invited to inspect student AI science exhibits on Thursday, Oct 15.",
    read: true,
    channel: "app",
    createdAt: "2 days ago",
  },
];

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: "em-1",
    name: "Metropolitan Women & Girls Police Station",
    type: "Police",
    phoneNumber: "+1 (555) 911-2020",
    address: "Civic Center Ave, Sector 4 (Rapid Response Post)",
    distanceKm: 0.8,
    latitude: 33.7182,
    longitude: 73.0605,
    isActive: true,
  },
  {
    id: "em-2",
    name: "St. Jude Children & Maternity Trauma Center",
    type: "Hospital",
    phoneNumber: "+1 (555) 911-4040",
    address: "12 Medical Complex Road, West Wing",
    distanceKm: 1.4,
    latitude: 33.722,
    longitude: 73.068,
    isActive: true,
  },
  {
    id: "em-3",
    name: "National Emergency & Rescue 1122 Helpline",
    type: "Helpline",
    phoneNumber: "1122",
    address: "Central Dispatch Hotline (24/7 Priority)",
    distanceKm: 2.1,
    latitude: 33.714,
    longitude: 73.052,
    isActive: true,
  },
  {
    id: "em-4",
    name: "SafeAI Campus Internal Security Desk",
    type: "Security",
    phoneNumber: "+1 (555) 723-3240",
    address: "Main Gate Guardhouse & Dispatch Booth",
    distanceKm: 0.05,
    latitude: 33.72,
    longitude: 73.06,
    isActive: true,
  },
];

export const INITIAL_HOMEWORK: HomeworkItem[] = [
  {
    id: "hw-1",
    title: "Chapter 5: Light-Dependent Reactions Diagram",
    description: "Draw and label the thylakoid membrane, ATP synthase, and electron transport chain. Explain the photolysis of water.",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    dueDate: "Tomorrow, 4:00 PM",
    assignedBy: "Dr. Amina Qureshi",
    submissionsCount: 22,
    totalStudents: 28,
    isCompletedByStudent: true,
  },
  {
    id: "hw-2",
    title: "Quadratic Formula Word Problems",
    description: "Solve problems 14 through 22 from Page 118 of the textbook. Show the discriminant calculation for each root.",
    subject: "Mathematics & Algebra",
    className: "Grade 10 - Lily",
    dueDate: "In 2 days, 9:00 AM",
    assignedBy: "Ms. Hiba Rashid",
    submissionsCount: 16,
    totalStudents: 28,
    isCompletedByStudent: false,
  },
  {
    id: "hw-3",
    title: "Python Loops and Functions Exercise",
    description: "Implement a student grade calculator function that accepts numerical scores and returns letter grades with validation.",
    subject: "Computer Science & AI",
    className: "Grade 10 - Lily",
    dueDate: "Friday, 11:59 PM",
    assignedBy: "Engr. Noor Fatima",
    submissionsCount: 10,
    totalStudents: 28,
    isCompletedByStudent: false,
  },
  {
    id: "hw-4",
    title: "Ecosystems & Food Chains Diagram",
    description: "Draw and label a temperate forest food web including primary producers, secondary consumers, and apex predators.",
    subject: "General Science",
    className: "Grade 8 - Daisy",
    dueDate: "Tomorrow, 3:00 PM",
    assignedBy: "Engr. Noor Fatima",
    submissionsCount: 20,
    totalStudents: 25,
    isCompletedByStudent: true,
  },
  {
    id: "hw-5",
    title: "Linear Equations & Graphing Worksheet",
    description: "Complete exercises 1 to 10 on graphing slopes and identifying y-intercepts.",
    subject: "Mathematics",
    className: "Grade 8 - Daisy",
    dueDate: "Monday, 9:00 AM",
    assignedBy: "Ms. Hiba Rashid",
    submissionsCount: 14,
    totalStudents: 25,
    isCompletedByStudent: false,
  },
];


export const INITIAL_MARKS: MarkItem[] = [
  {
    id: "m-1",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Biology & Life Sciences",
    examType: "Mid-Term Examination",
    obtainedMarks: 94.5,
    totalMarks: 100,
    grade: "A+",
    teacherRemarks: "Exemplary grasp of cell metabolism and genetic mechanisms. Active participation in laboratory sessions.",
    date: "2026-09-02",
  },
  {
    id: "m-2",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Mathematics & Algebra",
    examType: "Monthly Quiz 3",
    obtainedMarks: 48,
    totalMarks: 50,
    grade: "A+",
    teacherRemarks: "Excellent precision in factoring polynomials. Neat working.",
    date: "2026-09-08",
  },
  {
    id: "m-3",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Computer Science & AI",
    examType: "Project Practical",
    obtainedMarks: 49,
    totalMarks: 50,
    grade: "A+",
    teacherRemarks: "Outstanding project on AI ethical algorithms.",
    date: "2026-08-25",
  },
  {
    id: "m-4",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Physics",
    examType: "Mid-Term Examination",
    obtainedMarks: 89,
    totalMarks: 100,
    grade: "A",
    teacherRemarks: "Good conceptual understanding of Newtonian dynamics; practice numerical problems on projectile motion.",
    date: "2026-09-01",
  },
  {
    id: "m-5",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    subject: "General Science",
    examType: "Mid-Term Examination",
    obtainedMarks: 91,
    totalMarks: 100,
    grade: "A+",
    teacherRemarks: "Exceptional diagrams and clarity in describing plant cell vacuoles and osmosis.",
    date: "2026-09-03",
  },
  {
    id: "m-6",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    subject: "Mathematics",
    examType: "Monthly Quiz 2",
    obtainedMarks: 44,
    totalMarks: 50,
    grade: "A",
    teacherRemarks: "Strong algebraic manipulation skills. Continue practicing simultaneous linear equations.",
    date: "2026-09-06",
  },
  {
    id: "m-7",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    subject: "English Literature",
    examType: "Essay Assessment",
    obtainedMarks: 46,
    totalMarks: 50,
    grade: "A+",
    teacherRemarks: "Insightful literary analysis and eloquent vocabulary in the poetry comparison essay.",
    date: "2026-09-09",
  },
];


export const INITIAL_DOCUMENTS: RAGDocument[] = [
  {
    id: "doc-1",
    title: "Grade 10 Biology - Chapter 5: Photosynthesis & Respiration",
    filename: "Biology_Chapter_5_Photosynthesis.pdf",
    fileType: "pdf",
    fileSizeKb: 3420,
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    status: "indexed",
    chunksCount: 18,
    uploadedAt: "2026-09-01",
    summary: "Comprehensive syllabus guide covering light & dark reactions, chlorophyll absorption spectra, Calvin cycle, and aerobic ATP synthesis.",
  },
  {
    id: "doc-2",
    title: "Grade 10 Mathematics - Chapter 3: Quadratic Equations & Parabolas",
    filename: "Math_Grade10_Quadratic_Equations.pdf",
    fileType: "pdf",
    fileSizeKb: 2180,
    subject: "Mathematics & Algebra",
    className: "Grade 10 - Lily",
    status: "indexed",
    chunksCount: 14,
    uploadedAt: "2026-09-03",
    summary: "Factoring quadratics, completing the square, the quadratic formula x = (-b ± √(b² - 4ac))/(2a), and nature of roots.",
  },
  {
    id: "doc-3",
    title: "SafeAI Campus Safety Protocol & Emergency Evacuation Manual",
    filename: "SafeAI_Campus_Safety_Policy_2026.pdf",
    fileType: "pdf",
    fileSizeKb: 1450,
    subject: "School Policies & Safety",
    className: "All Classes",
    status: "indexed",
    chunksCount: 10,
    uploadedAt: "2026-08-20",
    summary: "School perimeter security, visitor check-in, SOS panic trigger procedures, assembly point protocols, and medical triage steps.",
  },
];

export const INITIAL_DOCUMENT_CHUNKS: DocumentChunk[] = [
  {
    id: "chk-1",
    documentId: "doc-1",
    chunkIndex: 1,
    page: 42,
    content: "Photosynthesis is the biological process by which green plants, algae, and cyanobacteria convert light energy, primarily from the Sun, into chemical energy stored in glucose. The overall balanced chemical equation is: 6CO2 + 6H2O + light energy -> C6H12O6 + 6O2. It occurs inside specialized cellular organelles called chloroplasts, which contain light-absorbing pigments termed chlorophyll.",
  },
  {
    id: "chk-2",
    documentId: "doc-1",
    chunkIndex: 2,
    page: 44,
    content: "The photosynthesis process occurs in two primary stages: 1) The Light-Dependent Reactions, which take place across the thylakoid membranes where light energy splits water molecules (photolysis) producing oxygen, ATP, and NADPH. 2) The Light-Independent Reactions (Calvin Cycle), which occur within the stroma and utilize ATP and NADPH to fix atmospheric carbon dioxide into high-energy sugars such as G3P and glucose.",
  },
  {
    id: "chk-3",
    documentId: "doc-1",
    chunkIndex: 3,
    page: 48,
    content: "Cellular respiration is the complementary metabolic pathway where cells break down glucose in the presence of oxygen to release usable chemical energy in the form of Adenosine Triphosphate (ATP). The equation is C6H12O6 + 6O2 -> 6CO2 + 6H2O + 36-38 ATP. The three key phases are Glycolysis (in cytoplasm), the Krebs Cycle (in mitochondrial matrix), and the Electron Transport Chain (inner mitochondrial cristae).",
  },
  {
    id: "chk-4",
    documentId: "doc-2",
    chunkIndex: 1,
    page: 72,
    content: "A quadratic equation is a second-degree polynomial equation of the standard form ax² + bx + c = 0, where a, b, and c are real constants and a ≠ 0. The solutions or roots can be derived using the quadratic formula: x = (-b ± √(b² - 4ac)) / (2a). The term Δ = b² - 4ac is called the discriminant. If Δ > 0, the equation has two distinct real roots; if Δ = 0, exactly one real root (repeated); if Δ < 0, two conjugate complex roots.",
  },
  {
    id: "chk-5",
    documentId: "doc-2",
    chunkIndex: 2,
    page: 78,
    content: "Methods for solving quadratic equations include: 1) Factoring by grouping or middle-term splitting. 2) Completing the square method. 3) Applying the quadratic formula. In real-world applications, parabolas model projectile motion, architectural arches, satellite dishes, and revenue optimization curves.",
  },
  {
    id: "chk-6",
    documentId: "doc-3",
    chunkIndex: 1,
    page: 5,
    content: "SafeAI Campus Emergency & SOS Protocol: If an emergency, security concern, or health anomaly arises, students can press the red SOS Panic Button in the SafeAI Student App or smart safety badges. Activation automatically: 1) Dispatches instant SMS and push alerts with live GPS coordinates to verified parents. 2) Rings the Central Security Control Room. 3) Alerts designated female campus safety officers and the nearest rapid response police precinct.",
  },
  {
    id: "chk-7",
    documentId: "doc-3",
    chunkIndex: 2,
    page: 8,
    content: "Geofencing & Campus Gate Protocols: The school campus boundary is protected by an active virtual geofence. When a student passes the biometric or RFID entry gate, parents immediately receive automated notification: 'Your daughter [Name] safely reached school at [Time]'. If an unscheduled exit occurs before dismissal hours, high-priority safety alerts are generated to guardians and security chiefs.",
  },
];

export const INITIAL_MCQS: MCQQuestion[] = [
  {
    id: "mcq-1",
    question: "Where do the light-dependent reactions of photosynthesis take place inside a plant cell?",
    options: {
      A: "Stroma of the chloroplast",
      B: "Thylakoid membranes",
      C: "Outer mitochondrial membrane",
      D: "Cytoplasm",
    },
    correctAnswer: "B",
    explanation: "According to Biology Chapter 5 (p. 44), light-dependent reactions occur across the thylakoid membranes, where chlorophyll pigments absorb photons and drive photolysis of water.",
    difficulty: "Easy",
  },
  {
    id: "mcq-2",
    question: "What is the primary function of the Calvin Cycle during photosynthesis?",
    options: {
      A: "To split water molecules into oxygen and protons",
      B: "To synthesize ATP using proton gradients",
      C: "To fix atmospheric CO2 into high-energy sugars using ATP and NADPH",
      D: "To absorb blue and red wavelengths of light",
    },
    correctAnswer: "C",
    explanation: "The Calvin Cycle (light-independent phase in the stroma) uses chemical energy from ATP and reducing power from NADPH to fix CO2 into glucose (p. 44).",
    difficulty: "Medium",
  },
  {
    id: "mcq-3",
    question: "For a quadratic equation ax² + bx + c = 0, what does a discriminant value of Δ = b² - 4ac < 0 indicate?",
    options: {
      A: "Two distinct real roots",
      B: "One repeated real root",
      C: "Two conjugate complex roots (no real roots)",
      D: "A linear equation",
    },
    correctAnswer: "C",
    explanation: "When Δ < 0, the square root √(Δ) yields an imaginary quantity, indicating two complex conjugate roots (Math Chapter 3, p. 72).",
    difficulty: "Medium",
  },
  {
    id: "mcq-4",
    question: "What immediate action is automatically triggered when a student activates the SafeAI SOS Emergency feature?",
    options: {
      A: "The phone resets all stored passwords",
      B: "Instant push & SMS alerts with live GPS are sent to parents, security, and nearest rapid response precinct",
      C: "The student's attendance is marked absent",
      D: "The exam timer is restarted",
    },
    correctAnswer: "B",
    explanation: "The Campus Safety Manual Section 2 specifies that SOS sends real-time coordinates, notifies parents instantly, and alerts campus security and emergency response teams.",
    difficulty: "Easy",
  },
  {
    id: "mcq-5",
    question: "How many net ATP molecules are typically produced per glucose molecule during aerobic cellular respiration?",
    options: {
      A: "2 ATP",
      B: "12-14 ATP",
      C: "36-38 ATP",
      D: "100 ATP",
    },
    correctAnswer: "C",
    explanation: "Aerobic cellular respiration completes glycolysis, the Krebs cycle, and electron transport chain phosphorylation, generating 36 to 38 ATP per glucose molecule (Biology p. 48).",
    difficulty: "Hard",
  },
];

export const INITIAL_FLASHCARDS: Flashcard[] = [
  {
    id: "fc-1",
    topic: "Photosynthesis",
    subject: "Biology",
    question: "What is Photolysis of Water?",
    answer: "The photochemical splitting of H2O into electrons, protons (H+), and molecular oxygen (O2) in photosystem II during light-dependent reactions.",
  },
  {
    id: "fc-2",
    topic: "Cellular Respiration",
    subject: "Biology",
    question: "Where does the Krebs Cycle occur?",
    answer: "In the mitochondrial matrix of eukaryotic cells.",
  },
  {
    id: "fc-3",
    topic: "Quadratic Equations",
    subject: "Mathematics",
    question: "What is the Quadratic Formula?",
    answer: "x = (-b ± √(b² - 4ac)) / (2a)",
  },
  {
    id: "fc-4",
    topic: "Safety & Geofencing",
    subject: "Campus Safety",
    question: "What triggers an automated parent departure notification?",
    answer: "When a student scans their QR badge or taps their RFID card at the departure turnstile.",
  },
];

export const INITIAL_STUDENT_ALERTS: StudentAlert[] = [
  {
    id: "alt-1",
    targetType: "individual",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    className: "Grade 10 - Lily",
    category: "medical",
    severity: "high",
    title: "Medical Flag: Inhaler Kept in School Clinic",
    message: "Sara experienced mild exercise-induced wheezing during morning P.E. Clinic nurse administered prescribed Salbutamol inhaler. She has rested and returned to class safely.",
    channels: ["sms", "push", "email"],
    deliveryStatus: "delivered",
    deliveredCount: 3,
    readCount: 2,
    totalRecipients: 1,
    dispatchedBy: "Nurse Zainab (Campus Health)",
    createdAt: "Today at 10:15 AM",
    actionRequired: false,
  },
  {
    id: "alt-2",
    targetType: "individual",
    studentId: "stu-2",
    studentName: "Ayesha Khan",
    className: "Grade 10 - Lily",
    category: "behavioral",
    severity: "normal",
    title: "Behavioral Commendation: Outstanding Peer Mentorship",
    message: "Ayesha was awarded Student of the Week commendation for guiding 8th grade juniors during AI Robotics workshop.",
    channels: ["push", "email"],
    deliveryStatus: "delivered",
    deliveredCount: 2,
    readCount: 2,
    totalRecipients: 1,
    dispatchedBy: "Dr. Amina Qureshi",
    createdAt: "Yesterday at 02:30 PM",
    actionRequired: false,
  },
  {
    id: "alt-3",
    targetType: "all",
    category: "emergency",
    severity: "critical",
    title: "School-wide Emergency Evacuation Drill Completed",
    message: "Routine campus earthquake response and evacuation drill completed successfully in 2 minutes 45 seconds. All 110 students safely assembled at West Lawn.",
    channels: ["sms", "push", "email", "whatsapp"],
    deliveryStatus: "delivered",
    deliveredCount: 110,
    readCount: 98,
    totalRecipients: 110,
    dispatchedBy: "Principal Farah Qureshi",
    createdAt: "Sep 10, 2026 at 09:30 AM",
    actionRequired: false,
  },
  {
    id: "alt-4",
    targetType: "class",
    className: "Grade 10 - Lily",
    category: "academic",
    severity: "high",
    title: "Exam Schedule Reminder: Mid-Term Chemistry Practical",
    message: "Mid-Term Chemistry lab practicals will commence on Monday at 08:30 AM in Science Lab 3. Full lab coats and safety goggles mandatory.",
    channels: ["sms", "push"],
    deliveryStatus: "delivered",
    deliveredCount: 28,
    readCount: 26,
    totalRecipients: 28,
    dispatchedBy: "Academic Coordinator",
    createdAt: "Sep 08, 2026 at 04:00 PM",
  },
];

export const INITIAL_USER_ACCOUNTS: UserAccount[] = [
  {
    id: "usr-1",
    fullName: "Principal Farah Qureshi",
    email: "admin@safeaischool.edu",
    phone: "+1 (555) 019-2831",
    role: "admin",
    status: "active",
    createdAt: "2025-08-01",
    lastLogin: "Today at 08:00 AM",
    employeeId: "ADM-001",
    department: "Executive Board & Governance",
  },
  {
    id: "usr-2",
    fullName: "Dr. Amina Qureshi",
    email: "teacher@safeaischool.edu",
    phone: "+1 (555) 883-9102",
    role: "teacher",
    status: "active",
    createdAt: "2025-08-15",
    lastLogin: "Today at 07:30 AM",
    employeeId: "TEA-882",
    department: "Science & Biology",
    qualification: "Ph.D. in Cellular Biology",
    assignedClasses: ["Grade 10 - Lily", "Grade 9 - Rose"],
  },
  {
    id: "usr-3",
    fullName: "Ms. Hiba Rashid",
    email: "hiba.rashid@faculty.safeaischool.edu",
    phone: "+1 (555) 772-4019",
    role: "teacher",
    status: "active",
    createdAt: "2025-09-01",
    lastLogin: "Today at 07:45 AM",
    employeeId: "TEA-883",
    department: "Mathematics & Statistics",
    qualification: "M.Sc. Pure Mathematics",
    assignedClasses: ["Grade 10 - Lily", "Grade 10 - Jasmine"],
  },
  {
    id: "usr-4",
    fullName: "Mrs. Sarah Jenkins",
    email: "sarah.jenkins@faculty.safeaischool.edu",
    phone: "+1 (555) 441-2093",
    role: "teacher",
    status: "suspended",
    createdAt: "2025-09-10",
    lastLogin: "Sep 05, 2026",
    employeeId: "TEA-884",
    department: "Humanities & English",
    qualification: "M.A. English Literature",
    assignedClasses: ["Grade 10 - Lily", "Grade 9 - Rose"],
  },
  {
    id: "usr-5",
    fullName: "Sara Ahmed",
    email: "sara.ahmed@student.safeaischool.edu",
    phone: "+1 (555) 349-2810",
    role: "student",
    status: "active",
    createdAt: "2026-01-10",
    lastLogin: "Today at 07:45 AM",
    rollNumber: "SAF-2026-042",
    className: "Grade 10 - Lily",
    parentId: "par-1",
    parentName: "Tariq Ahmed",
    rfidCardId: "RFID-99482",
    qrCodeToken: "QR-SARA-AHMED-10A-99482",
  },
  {
    id: "usr-6",
    fullName: "Ayesha Khan",
    email: "ayesha.khan@student.safeaischool.edu",
    phone: "+1 (555) 782-9011",
    role: "student",
    status: "active",
    createdAt: "2026-01-12",
    lastLogin: "Today at 07:52 AM",
    rollNumber: "SAF-2026-043",
    className: "Grade 10 - Lily",
    parentId: "par-2",
    parentName: "Yasmin Khan",
    rfidCardId: "RFID-99483",
    qrCodeToken: "QR-AYESHA-KHAN-10A-99483",
  },
  {
    id: "usr-7",
    fullName: "Tariq Ahmed",
    email: "tariq.ahmed@parent.safeaischool.edu",
    phone: "+1 (555) 349-2810",
    role: "parent",
    status: "active",
    createdAt: "2026-01-10",
    lastLogin: "Today at 07:46 AM",
    relationship: "Father",
    studentNames: ["Sara Ahmed"],
  },
  {
    id: "usr-8",
    fullName: "Yasmin Khan",
    email: "yasmin.khan@parent.safeaischool.edu",
    phone: "+1 (555) 782-9011",
    role: "parent",
    status: "active",
    createdAt: "2026-01-12",
    lastLogin: "Today at 07:53 AM",
    relationship: "Mother",
    studentNames: ["Ayesha Khan"],
  },
];

export const DEFAULT_RBAC_PERMISSIONS: Record<string, RBACRolePermissions> = {
  admin: {
    role: "admin",
    canMarkAttendance: true,
    canScanQrRfid: true,
    canIssueEmergencyAlerts: true,
    canIssueMedicalAlerts: true,
    canManageUsers: true,
    canManageStructure: true,
    canUploadCurriculum: true,
    canViewAuditLogs: true,
    canAssignHomework: true,
    canRecordMarks: true,
  },
  teacher: {
    role: "teacher",
    canMarkAttendance: true,
    canScanQrRfid: true,
    canIssueEmergencyAlerts: false,
    canIssueMedicalAlerts: true,
    canManageUsers: false,
    canManageStructure: false,
    canUploadCurriculum: true,
    canViewAuditLogs: false,
    canAssignHomework: true,
    canRecordMarks: true,
  },
  parent: {
    role: "parent",
    canMarkAttendance: false,
    canScanQrRfid: false,
    canIssueEmergencyAlerts: true, // SOS request
    canIssueMedicalAlerts: false,
    canManageUsers: false,
    canManageStructure: false,
    canUploadCurriculum: false,
    canViewAuditLogs: false,
    canAssignHomework: false,
    canRecordMarks: false,
  },
  student: {
    role: "student",
    canMarkAttendance: false,
    canScanQrRfid: false,
    canIssueEmergencyAlerts: true, // SOS panic button
    canIssueMedicalAlerts: false,
    canManageUsers: false,
    canManageStructure: false,
    canUploadCurriculum: false,
    canViewAuditLogs: false,
    canAssignHomework: false,
    canRecordMarks: false,
  },
};

export const INITIAL_ACADEMIC_EVENTS: AcademicEvent[] = [
  {
    id: "evt-1",
    title: "Fall Semester 2026 Session Commences",
    type: "term",
    startDate: "2026-08-15",
    endDate: "2026-12-22",
    term: "Fall 2026",
    description: "Beginning of academic term for all grades.",
    isImportant: true,
  },
  {
    id: "evt-2",
    title: "Mid-Term Examinations Week",
    type: "exam",
    startDate: "2026-10-12",
    endDate: "2026-10-19",
    term: "Fall 2026",
    description: "Centralized campus exams across all secondary grades.",
    isImportant: true,
  },
  {
    id: "evt-3",
    title: "Parent-Teacher Conference (PTC)",
    type: "meeting",
    startDate: "2026-10-24",
    endDate: "2026-10-24",
    term: "Fall 2026",
    description: "In-person academic review, attendance review, and learning goal alignment.",
    isImportant: true,
  },
  {
    id: "evt-4",
    title: "Annual STEM & Girls in AI Robotics Fair",
    type: "event",
    startDate: "2026-11-06",
    endDate: "2026-11-07",
    term: "Fall 2026",
    description: "Student AI science project exhibition and robotics demonstrations.",
    isImportant: false,
  },
  {
    id: "evt-5",
    title: "National Autumn Mid-Semester Break",
    type: "holiday",
    startDate: "2026-11-14",
    endDate: "2026-11-18",
    term: "Fall 2026",
    description: "Campus closed for scheduled national holiday.",
    isImportant: false,
  },
  {
    id: "evt-6",
    title: "Final Term Examinations & Results Declaration",
    type: "exam",
    startDate: "2026-12-10",
    endDate: "2026-12-21",
    term: "Fall 2026",
    description: "Cumulative final examinations followed by report card distribution.",
    isImportant: true,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // Monday
  { id: "tt-1", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 1, startTime: "08:00 AM", endTime: "08:50 AM", subjectName: "Biology & Life Sciences", teacherName: "Dr. Amina Qureshi", roomNumber: "Lab 3" },
  { id: "tt-2", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 2, startTime: "08:55 AM", endTime: "09:45 AM", subjectName: "Mathematics & Algebra", teacherName: "Ms. Hiba Rashid", roomNumber: "Lab 3" },
  { id: "tt-3", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 3, startTime: "09:50 AM", endTime: "10:40 AM", subjectName: "English Literature", teacherName: "Mrs. Sarah Jenkins", roomNumber: "Lab 3" },
  { id: "tt-4", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 4, startTime: "11:10 AM", endTime: "12:00 PM", subjectName: "Computer Science & AI", teacherName: "Engr. Noor Fatima", roomNumber: "AI Lab 1" },
  { id: "tt-5", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 5, startTime: "12:05 PM", endTime: "12:55 PM", subjectName: "Physics", teacherName: "Dr. Samira Al-Mansoor", roomNumber: "Lab 3" },
  { id: "tt-6", classId: "c-10a", className: "Grade 10 - Lily", day: "Monday", periodNumber: 6, startTime: "01:00 PM", endTime: "01:45 PM", subjectName: "Physical Education & Self-Defense", teacherName: "Coach Yasmin", roomNumber: "Sports Hall" },
  // Tuesday
  { id: "tt-7", classId: "c-10a", className: "Grade 10 - Lily", day: "Tuesday", periodNumber: 1, startTime: "08:00 AM", endTime: "08:50 AM", subjectName: "Mathematics & Algebra", teacherName: "Ms. Hiba Rashid", roomNumber: "Lab 3" },
  { id: "tt-8", classId: "c-10a", className: "Grade 10 - Lily", day: "Tuesday", periodNumber: 2, startTime: "08:55 AM", endTime: "09:45 AM", subjectName: "Biology & Life Sciences", teacherName: "Dr. Amina Qureshi", roomNumber: "Bio Lab" },
  { id: "tt-9", classId: "c-10a", className: "Grade 10 - Lily", day: "Tuesday", periodNumber: 3, startTime: "09:50 AM", endTime: "10:40 AM", subjectName: "Physics", teacherName: "Dr. Samira Al-Mansoor", roomNumber: "Lab 3" },
  { id: "tt-10", classId: "c-10a", className: "Grade 10 - Lily", day: "Tuesday", periodNumber: 4, startTime: "11:10 AM", endTime: "12:00 PM", subjectName: "English Literature", teacherName: "Mrs. Sarah Jenkins", roomNumber: "Lab 3" },
  { id: "tt-11", classId: "c-10a", className: "Grade 10 - Lily", day: "Tuesday", periodNumber: 5, startTime: "12:05 PM", endTime: "12:55 PM", subjectName: "Computer Science & AI", teacherName: "Engr. Noor Fatima", roomNumber: "AI Lab 1" },
  // Wednesday
  { id: "tt-12", classId: "c-10a", className: "Grade 10 - Lily", day: "Wednesday", periodNumber: 1, startTime: "08:00 AM", endTime: "08:50 AM", subjectName: "Computer Science & AI", teacherName: "Engr. Noor Fatima", roomNumber: "AI Lab 1" },
  { id: "tt-13", classId: "c-10a", className: "Grade 10 - Lily", day: "Wednesday", periodNumber: 2, startTime: "08:55 AM", endTime: "09:45 AM", subjectName: "Biology & Life Sciences", teacherName: "Dr. Amina Qureshi", roomNumber: "Bio Lab" },
  { id: "tt-14", classId: "c-10a", className: "Grade 10 - Lily", day: "Wednesday", periodNumber: 3, startTime: "09:50 AM", endTime: "10:40 AM", subjectName: "Mathematics & Algebra", teacherName: "Ms. Hiba Rashid", roomNumber: "Lab 3" },
  { id: "tt-15", classId: "c-10a", className: "Grade 10 - Lily", day: "Wednesday", periodNumber: 4, startTime: "11:10 AM", endTime: "12:00 PM", subjectName: "Physics", teacherName: "Dr. Samira Al-Mansoor", roomNumber: "Lab 3" },
  { id: "tt-16", classId: "c-10a", className: "Grade 10 - Lily", day: "Wednesday", periodNumber: 5, startTime: "12:05 PM", endTime: "12:55 PM", subjectName: "English Literature", teacherName: "Mrs. Sarah Jenkins", roomNumber: "Lab 3" },
  // Thursday
  { id: "tt-17", classId: "c-10a", className: "Grade 10 - Lily", day: "Thursday", periodNumber: 1, startTime: "08:00 AM", endTime: "08:50 AM", subjectName: "Biology & Life Sciences", teacherName: "Dr. Amina Qureshi", roomNumber: "Lab 3" },
  { id: "tt-18", classId: "c-10a", className: "Grade 10 - Lily", day: "Thursday", periodNumber: 2, startTime: "08:55 AM", endTime: "09:45 AM", subjectName: "Mathematics & Algebra", teacherName: "Ms. Hiba Rashid", roomNumber: "Lab 3" },
  { id: "tt-19", classId: "c-10a", className: "Grade 10 - Lily", day: "Thursday", periodNumber: 3, startTime: "09:50 AM", endTime: "10:40 AM", subjectName: "Physics", teacherName: "Dr. Samira Al-Mansoor", roomNumber: "Lab 3" },
  { id: "tt-20", classId: "c-10a", className: "Grade 10 - Lily", day: "Thursday", periodNumber: 4, startTime: "11:10 AM", endTime: "12:00 PM", subjectName: "Computer Science & AI", teacherName: "Engr. Noor Fatima", roomNumber: "AI Lab 1" },
  // Friday
  { id: "tt-21", classId: "c-10a", className: "Grade 10 - Lily", day: "Friday", periodNumber: 1, startTime: "08:00 AM", endTime: "08:50 AM", subjectName: "Mathematics & Algebra", teacherName: "Ms. Hiba Rashid", roomNumber: "Lab 3" },
  { id: "tt-22", classId: "c-10a", className: "Grade 10 - Lily", day: "Friday", periodNumber: 2, startTime: "08:55 AM", endTime: "09:45 AM", subjectName: "Biology & Life Sciences", teacherName: "Dr. Amina Qureshi", roomNumber: "Bio Lab" },
  { id: "tt-23", classId: "c-10a", className: "Grade 10 - Lily", day: "Friday", periodNumber: 3, startTime: "09:50 AM", endTime: "10:40 AM", subjectName: "Islamic Studies & Ethics", teacherName: "Ustadh Bilal", roomNumber: "Hall 2" },
  { id: "tt-24", classId: "c-10a", className: "Grade 10 - Lily", day: "Friday", periodNumber: 4, startTime: "11:00 AM", endTime: "11:45 AM", subjectName: "STEM Mentorship Circle", teacherName: "Principal Farah Qureshi", roomNumber: "Auditorium" },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-1",
    timestamp: "Today at 10:15 AM",
    actorName: "Nurse Zainab",
    actorRole: "teacher",
    action: "ALERT_DISPATCHED",
    targetEntity: "Sara Ahmed (Medical Flag)",
    ipAddress: "192.168.1.45 (Campus Health Clinic)",
    severity: "warning",
    details: "Dispatched high-priority Medical Flag to parents via SMS, Push, and Email regarding clinic inhaler administration.",
  },
  {
    id: "aud-2",
    timestamp: "Today at 08:15 AM",
    actorName: "Security Turnstile Engine",
    actorRole: "admin",
    action: "ATTENDANCE_SCANNED",
    targetEntity: "Sara Ahmed (QR-SARA-AHMED-10A-99482)",
    ipAddress: "10.0.4.12 (North Gate Turnstile 2)",
    severity: "info",
    details: "Optical QR code scan validated. Status: Present. Automatic arrival WhatsApp message sent to Tariq Ahmed.",
  },
  {
    id: "aud-3",
    timestamp: "Today at 07:55 AM",
    actorName: "Principal Farah Qureshi",
    actorRole: "admin",
    action: "USER_STATUS_UPDATED",
    targetEntity: "Mrs. Sarah Jenkins (TEA-884)",
    ipAddress: "192.168.1.10 (Executive Office)",
    severity: "critical",
    details: "Teacher account status changed from Active to Suspended pending compliance clearance.",
  },
  {
    id: "aud-4",
    timestamp: "Yesterday at 04:30 PM",
    actorName: "Dr. Amina Qureshi",
    actorRole: "teacher",
    action: "RAG_DOCUMENT_INDEXED",
    targetEntity: "Biology_Grade10_Photosynthesis.pdf",
    ipAddress: "192.168.1.88 (Science Faculty Room)",
    severity: "info",
    details: "Uploaded 48 KB PDF. 6 document chunks vectorized into pgvector memory store.",
  },
  {
    id: "aud-5",
    timestamp: "Sep 10, 2026 at 09:30 AM",
    actorName: "Principal Farah Qureshi",
    actorRole: "admin",
    action: "EMERGENCY_BROADCAST",
    targetEntity: "All 110 Student Guardians",
    ipAddress: "192.168.1.10 (Security Desk)",
    severity: "critical",
    details: "School-wide evacuation drill alert dispatched via SMS, Push, Email, and WhatsApp.",
  },
  {
    id: "aud-6",
    timestamp: "Sep 09, 2026 at 11:20 AM",
    actorName: "IT Administrator",
    actorRole: "admin",
    action: "TIMETABLE_CONFIGURED",
    targetEntity: "Grade 10 - Lily Schedule",
    ipAddress: "192.168.1.15 (Server Room)",
    severity: "info",
    details: "Updated Friday timetable period 4 to STEM Mentorship Circle.",
  },
];

export const INITIAL_TEACHER_COMPLIANCE: TeacherCompliance[] = [
  {
    teacherId: "tea-1",
    teacherName: "Dr. Amina Qureshi",
    department: "Science & Biology",
    attendanceSubmissionRate: 98.5,
    lessonPlansUploaded: 4,
    lessonPlansRequired: 4,
    homeworkAssignedCount: 6,
    marksEnteredRate: 100,
    complianceStatus: "compliant",
    lastActive: "Today at 07:45 AM",
  },
  {
    teacherId: "tea-2",
    teacherName: "Ms. Hiba Rashid",
    department: "Mathematics & Statistics",
    attendanceSubmissionRate: 95.0,
    lessonPlansUploaded: 3,
    lessonPlansRequired: 4,
    homeworkAssignedCount: 5,
    marksEnteredRate: 92.0,
    complianceStatus: "compliant",
    lastActive: "Today at 08:10 AM",
  },
  {
    teacherId: "tea-3",
    teacherName: "Engr. Noor Fatima",
    department: "Computer Science & AI",
    attendanceSubmissionRate: 92.0,
    lessonPlansUploaded: 4,
    lessonPlansRequired: 4,
    homeworkAssignedCount: 4,
    marksEnteredRate: 88.0,
    complianceStatus: "compliant",
    lastActive: "Yesterday at 03:15 PM",
  },
  {
    teacherId: "tea-4",
    teacherName: "Dr. Samira Al-Mansoor",
    department: "Physics",
    attendanceSubmissionRate: 84.0,
    lessonPlansUploaded: 2,
    lessonPlansRequired: 4,
    homeworkAssignedCount: 2,
    marksEnteredRate: 75.0,
    complianceStatus: "warning",
    lastActive: "2 days ago",
  },
  {
    teacherId: "tea-5",
    teacherName: "Mrs. Sarah Jenkins",
    department: "Humanities & English",
    attendanceSubmissionRate: 68.0,
    lessonPlansUploaded: 1,
    lessonPlansRequired: 4,
    homeworkAssignedCount: 1,
    marksEnteredRate: 50.0,
    complianceStatus: "overdue",
    lastActive: "Sep 05, 2026",
  },
];

export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: "mat-1",
    title: "Chapter 5: Photosynthesis & Calvin Cycle Core Notes",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    lessonChapter: "Chapter 5: Bioenergetics",
    type: "pdf",
    fileUrl: "/materials/biology_ch5_photosynthesis.pdf",
    description: "Comprehensive handwritten diagrams of the thylakoid membrane, light-dependent photolysis of water, and Calvin cycle carbon fixation.",
    uploadedBy: "Dr. Amina Qureshi",
    uploadedAt: "Today at 09:15 AM",
    fileSizeKb: 1420,
    ragIndexed: true,
  },
  {
    id: "mat-2",
    title: "Cellular Respiration Lecture Slide Deck",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    lessonChapter: "Chapter 6: Cellular Respiration",
    type: "slide_deck",
    fileUrl: "/materials/slides_cellular_respiration.pptx",
    description: "Classroom presentation slides covering glycolysis, Krebs citric acid cycle, and oxidative phosphorylation ATP yield.",
    uploadedBy: "Dr. Amina Qureshi",
    uploadedAt: "Yesterday at 03:40 PM",
    fileSizeKb: 3800,
    ragIndexed: false,
  },
  {
    id: "mat-3",
    title: "Video Lecture: Visualizing Mitochondrial Electron Transport",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    lessonChapter: "Chapter 6: Cellular Respiration",
    type: "video_tutorial",
    videoUrl: "https://www.youtube.com/watch?v=rdF50trSpeY",
    description: "14-minute 3D molecular animation explaining chemiosmosis and the rotating proton motor of ATP synthase.",
    uploadedBy: "Dr. Amina Qureshi",
    uploadedAt: "Sep 09, 2026",
    fileSizeKb: 0,
    ragIndexed: false,
  },
  {
    id: "mat-4",
    title: "Quadratic Formula & Root Derivations Master Worksheet",
    subject: "Mathematics & Algebra",
    className: "Grade 10 - Lily",
    lessonChapter: "Chapter 3: Quadratic Equations",
    type: "homework",
    fileUrl: "/materials/math_quadratic_worksheet.pdf",
    description: "Step-by-step problem sets covering discriminant analysis (b² - 4ac) and real vs imaginary root classification.",
    uploadedBy: "Ms. Hiba Rashid",
    uploadedAt: "Sep 08, 2026",
    fileSizeKb: 890,
    ragIndexed: true,
  },
  {
    id: "mat-5",
    title: "Fall 2026 Complete Biology Syllabus & Lab Rubric",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    lessonChapter: "Course Overview",
    type: "syllabus",
    fileUrl: "/materials/bio_fall2026_syllabus.pdf",
    description: "Institutional syllabus, terminal exam weightage, weekly schedule, and lab microscope safety requirements.",
    uploadedBy: "Dr. Amina Qureshi",
    uploadedAt: "Aug 20, 2026",
    fileSizeKb: 540,
    ragIndexed: true,
  },
  {
    id: "mat-6",
    title: "Python Data Structures & Algorithm Video Walkthrough",
    subject: "Computer Science & AI",
    className: "Grade 10 - Lily",
    lessonChapter: "Unit 2: Python Programming",
    type: "video_tutorial",
    videoUrl: "https://www.youtube.com/watch?v=kqtD5dpn9C8",
    description: "Hands-on coding walkthrough demonstrating dictionaries, recursion, and search algorithms.",
    uploadedBy: "Engr. Noor Fatima",
    uploadedAt: "Sep 07, 2026",
    fileSizeKb: 0,
    ragIndexed: false,
  },
];

export const INITIAL_PROGRESS_NOTES: StudentProgressNote[] = [
  {
    id: "pn-1",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    parentName: "Tariq Ahmed",
    teacherName: "Dr. Amina Qureshi",
    subject: "Biology & Life Sciences",
    category: "academic",
    note: "Sara demonstrated outstanding conceptual understanding during our microscope lab on stomata cell regulation. Her lab write-up was exemplary.",
    sentAt: "Today at 11:30 AM",
    read: true,
    channel: "whatsapp",
  },
  {
    id: "pn-2",
    studentId: "stu-2",
    studentName: "Ayesha Khan",
    parentName: "Yasmin Khan",
    teacherName: "Dr. Amina Qureshi",
    subject: "Biology & Life Sciences",
    category: "behavioral",
    note: "Ayesha stepped up wonderfully as table group leader today, assisting teammates with optical calibration. High praise for her team spirit!",
    sentAt: "Yesterday at 02:15 PM",
    read: true,
    channel: "app",
  },
  {
    id: "pn-3",
    studentId: "stu-3",
    studentName: "Fatima Noor",
    parentName: "Bilal Noor",
    teacherName: "Ms. Hiba Rashid",
    subject: "Mathematics & Algebra",
    category: "homework",
    note: "Fatima has made great progress with factoring quadratics. Please ensure she completes the review problems on Page 122 before the quiz.",
    sentAt: "Sep 10, 2026",
    read: false,
    channel: "sms",
  },
  {
    id: "pn-4",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    parentName: "Tariq Ahmed",
    teacherName: "Engr. Noor Fatima",
    subject: "General Science",
    category: "academic",
    note: "Zainab presented a magnificent ecosystem food web poster in class today! Her peer collaboration is commendable.",
    sentAt: "Today at 09:15 AM",
    read: true,
    channel: "app",
  },
];

export const INITIAL_PARENT_MESSAGES: ParentMessage[] = [
  {
    id: "pmsg-1",
    senderType: "teacher",
    senderName: "Dr. Amina Qureshi",
    senderRole: "Lead Biology Educator & Head of Science",
    recipientName: "Tariq Ahmed",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Mid-Term Lab Practical Readiness & Commendation",
    message: "Assalamu Alaikum Mr. Tariq, I would like to commend Sara on her thorough preparation for upcoming biology practicals. Her microscope slide preparation was among the top in Grade 10. We encourage her to keep up this dedication for the terminal exams.",
    timestamp: "Today at 10:45 AM",
    unread: true,
    channel: "app",
    category: "academic",
    replyCount: 1,
  },
  {
    id: "pmsg-2",
    senderType: "teacher",
    senderName: "Engr. Noor Fatima",
    senderRole: "Junior Science & AI Educator",
    recipientName: "Tariq Ahmed",
    studentId: "stu-5",
    studentName: "Zainab Ahmed",
    subject: "Zainab's Robotics Fair Project Selection",
    message: "Respected Guardian, Zainab has submitted an outstanding project proposal for the upcoming Girls STEM & Robotics exhibition (Solar Automated Hydroponics). We have approved her concept and assigned her to Lab 2.",
    timestamp: "Yesterday at 03:20 PM",
    unread: false,
    channel: "app",
    category: "academic",
    replyCount: 0,
  },
  {
    id: "pmsg-3",
    senderType: "admin",
    senderName: "Principal Farah Qureshi",
    senderRole: "School Executive Principal",
    recipientName: "All School Families",
    subject: "Official Announcement: Annual Parent-Teacher Academic Conference",
    message: "Dear Parents and Guardians, Our Fall Semester Parent-Teacher Academic Consultation Day is scheduled for Friday, Oct 24, 2026. Online 15-minute slot reservations with subject faculty will open via this portal next Monday. We look forward to partnering in your child's academic flourishing.",
    timestamp: "Sep 10, 2026",
    unread: false,
    channel: "email",
    category: "announcement",
    replyCount: 0,
  },
  {
    id: "pmsg-4",
    senderType: "teacher",
    senderName: "Ms. Hiba Rashid",
    senderRole: "Mathematics Department Lead",
    recipientName: "Tariq Ahmed",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Quadratic Equations Diagnostic Practice",
    message: "Dear Mr. Ahmed, Sara scored 48/50 on Monthly Quiz 3. She has a solid grasp of the quadratic formula. I have shared extra enrichment problems for discriminant analysis which will prepare her nicely for Olympiad math.",
    timestamp: "Sep 08, 2026",
    unread: false,
    channel: "sms",
    category: "academic",
    replyCount: 2,
  },
];

export const INITIAL_PAST_PAPERS: PastExamPaper[] = [
  {
    id: "pp-1",
    title: "Grade 10 Biology - Fall Mid-Term Examination 2025",
    subject: "Biology & Life Sciences",
    gradeLevel: 10,
    year: 2025,
    term: "Mid-Term",
    durationMinutes: 90,
    totalMarks: 100,
    fileSizeKb: 1420,
    hasSolutionKey: true,
  },
  {
    id: "pp-2",
    title: "Grade 10 Mathematics - Annual Terminal Exam 2025",
    subject: "Mathematics & Algebra",
    gradeLevel: 10,
    year: 2025,
    term: "Terminal",
    durationMinutes: 120,
    totalMarks: 100,
    fileSizeKb: 1680,
    hasSolutionKey: true,
  },
  {
    id: "pp-3",
    title: "Grade 10 Physics - Mid-Term Practical & Theory Paper 2024",
    subject: "Physics",
    gradeLevel: 10,
    year: 2024,
    term: "Mid-Term",
    durationMinutes: 90,
    totalMarks: 100,
    fileSizeKb: 1250,
    hasSolutionKey: true,
  },
  {
    id: "pp-4",
    title: "Grade 10 Computer Science - Python & Algorithms Final 2025",
    subject: "Computer Science & AI",
    gradeLevel: 10,
    year: 2025,
    term: "Terminal",
    durationMinutes: 90,
    totalMarks: 75,
    fileSizeKb: 980,
    hasSolutionKey: true,
  },
  {
    id: "pp-5",
    title: "Grade 8 General Science - Annual Examination 2025",
    subject: "General Science",
    gradeLevel: 8,
    year: 2025,
    term: "Annual",
    durationMinutes: 90,
    totalMarks: 80,
    fileSizeKb: 1100,
    hasSolutionKey: true,
  },
];

export const INITIAL_REVISION_CHECKLIST: RevisionChecklistItem[] = [
  {
    id: "rc-1",
    subject: "Biology & Life Sciences",
    chapter: "Chapter 5: Photosynthesis & Energy Transfer",
    topic: "Photolysis of water in Photosystem II & electron transport",
    isCompleted: true,
    importance: "high",
    notesSummary: "Split 2H2O into 4H+ + 4e- + O2. Produces NADPH and ATP via chemiosmosis.",
  },
  {
    id: "rc-2",
    subject: "Biology & Life Sciences",
    chapter: "Chapter 5: Photosynthesis & Energy Transfer",
    topic: "Calvin Cycle: Carbon fixation, reduction phase, and RuBP regeneration",
    isCompleted: true,
    importance: "high",
    notesSummary: "RuBisCO catalyzes CO2 with RuBP. 6 turns produce 1 glucose molecule.",
  },
  {
    id: "rc-3",
    subject: "Biology & Life Sciences",
    chapter: "Chapter 5: Photosynthesis & Energy Transfer",
    topic: "Limiting Factors: Light intensity, CO2 concentration, temperature curves",
    isCompleted: false,
    importance: "medium",
    notesSummary: "Graph plateau indicates secondary factor has become rate-limiting.",
  },
  {
    id: "rc-4",
    subject: "Mathematics & Algebra",
    chapter: "Chapter 3: Quadratic Equations & Parabolas",
    topic: "Quadratic Formula x = (-b ± √(b² - 4ac)) / (2a) derivation",
    isCompleted: true,
    importance: "high",
    notesSummary: "Always check for standard form ax² + bx + c = 0 before identifying coefficients.",
  },
  {
    id: "rc-5",
    subject: "Mathematics & Algebra",
    chapter: "Chapter 3: Quadratic Equations & Parabolas",
    topic: "Discriminant analysis (Δ > 0, Δ = 0, Δ < 0) for real vs complex roots",
    isCompleted: false,
    importance: "high",
    notesSummary: "Δ > 0: two real roots; Δ = 0: one repeated root; Δ < 0: two conjugate complex roots.",
  },
  {
    id: "rc-6",
    subject: "Physics",
    chapter: "Unit 2: Kinematics & Laws of Motion",
    topic: "Equations of uniformly accelerated motion (v = u + at, s = ut + 0.5at², v² = u² + 2as)",
    isCompleted: false,
    importance: "high",
    notesSummary: "Pay attention to sign conventions for upward (+g vs -g) projectile motion.",
  },
  {
    id: "rc-7",
    subject: "Computer Science & AI",
    chapter: "Unit 3: Algorithmic Thinking & Python",
    topic: "Recursion vs iteration and Big-O computational time complexity",
    isCompleted: true,
    importance: "medium",
    notesSummary: "Base case is mandatory in recursion to prevent stack overflow errors.",
  },
];

export const TIMED_PRACTICE_QUESTIONS: TimedPracticeQuestion[] = [
  {
    id: "tpq-1",
    question: "Which organelle component contains the enzymes necessary for the Calvin Cycle?",
    options: {
      A: "Thylakoid Lumen",
      B: "Stroma",
      C: "Outer membrane",
      D: "Cristae",
    },
    correctAnswer: "B",
    explanation: "The stroma of the chloroplast is the fluid-filled space containing RuBisCO and enzymes for carbon fixation.",
    subject: "Biology & Life Sciences",
  },
  {
    id: "tpq-2",
    question: "If a quadratic equation has discriminant Δ = 16, how many distinct real roots does it have?",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "Infinitely many",
    },
    correctAnswer: "C",
    explanation: "Since Δ = 16 > 0, the equation has two distinct real roots (x = (-b ± 4)/2a).",
    subject: "Mathematics & Algebra",
  },
  {
    id: "tpq-3",
    question: "What is the primary function of ATP synthase during photophosphorylation?",
    options: {
      A: "Splitting carbon dioxide",
      B: "Synthesizing ATP using the proton electrochemical gradient",
      C: "Absorbing green light photons",
      D: "Transporting electrons from ferredoxin to NADP+",
    },
    correctAnswer: "B",
    explanation: "ATP synthase harnesses the H+ concentration gradient across the thylakoid membrane to phosphorylate ADP into ATP.",
    subject: "Biology & Life Sciences",
  },
  {
    id: "tpq-4",
    question: "An object is thrown vertically upward with initial velocity u = 19.6 m/s. Taking g = 9.8 m/s², what is the time to reach maximum height?",
    options: {
      A: "1.0 second",
      B: "2.0 seconds",
      C: "3.5 seconds",
      D: "4.0 seconds",
    },
    correctAnswer: "B",
    explanation: "At maximum height, v = 0. Using v = u - gt => 0 = 19.6 - 9.8t => t = 2.0 s.",
    subject: "Physics",
  },
  {
    id: "tpq-5",
    question: "In Python, which keyword is used to exit prematurely from a loop?",
    options: {
      A: "return",
      B: "continue",
      C: "break",
      D: "pass",
    },
    correctAnswer: "C",
    explanation: "The 'break' statement terminates the current loop immediately and transfers execution to the statement following the loop.",
    subject: "Computer Science & AI",
  },
];


