import {
  Student,
  Parent,
  Teacher,
  SchoolClass,
  Subject,
  AttendanceRecord,
  NotificationItem,
  EmergencyContact,
  HomeworkItem,
  MarkItem,
  RAGDocument,
  DocumentChunk,
  MCQQuestion,
  Flashcard,
} from "./types";

export const INITIAL_CLASSES: SchoolClass[] = [
  { id: "c-10a", name: "Grade 10 - Lily", gradeLevel: 10, section: "A", roomNumber: "Lab 3", studentCount: 28 },
  { id: "c-10b", name: "Grade 10 - Jasmine", gradeLevel: 10, section: "B", roomNumber: "Hall 2", studentCount: 26 },
  { id: "c-9a", name: "Grade 9 - Rose", gradeLevel: 9, section: "A", roomNumber: "Room 101", studentCount: 30 },
  { id: "c-8a", name: "Grade 8 - Daisy", gradeLevel: 8, section: "A", roomNumber: "Room 204", studentCount: 25 },
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: "sub-1", name: "Biology & Life Sciences", code: "BIO-101", classId: "c-10a", teacherName: "Dr. Amina Qureshi" },
  { id: "sub-2", name: "Mathematics & Algebra", code: "MTH-102", classId: "c-10a", teacherName: "Ms. Hiba Rashid" },
  { id: "sub-3", name: "English Literature", code: "ENG-103", classId: "c-10a", teacherName: "Mrs. Sarah Jenkins" },
  { id: "sub-4", name: "Computer Science & AI", code: "CS-104", classId: "c-10a", teacherName: "Engr. Noor Fatima" },
  { id: "sub-5", name: "Physics", code: "PHY-105", classId: "c-10a", teacherName: "Dr. Samira Al-Mansoor" },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stu-1",
    userId: "u-stu-1",
    fullName: "Sara Ahmed",
    rollNumber: "SAF-2026-042",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-1",
    parentName: "Tariq Ahmed",
    parentPhone: "+1 (555) 349-2810",
    parentEmail: "tariq.ahmed@example.com",
    bloodGroup: "O+",
    rfidCardId: "RFID-99482",
    qrCodeToken: "QR-SARA-AHMED-10A-99482",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:45 AM",
    attendanceRate: 98.4,
  },
  {
    id: "stu-2",
    userId: "u-stu-2",
    fullName: "Ayesha Khan",
    rollNumber: "SAF-2026-043",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-2",
    parentName: "Yasmin Khan",
    parentPhone: "+1 (555) 782-9011",
    parentEmail: "yasmin.khan@example.com",
    bloodGroup: "A+",
    rfidCardId: "RFID-99483",
    qrCodeToken: "QR-AYESHA-KHAN-10A-99483",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:52 AM",
    attendanceRate: 96.0,
  },
  {
    id: "stu-3",
    userId: "u-stu-3",
    fullName: "Fatima Noor",
    rollNumber: "SAF-2026-044",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-3",
    parentName: "Bilal Noor",
    parentPhone: "+1 (555) 438-1192",
    parentEmail: "bilal.noor@example.com",
    bloodGroup: "B+",
    rfidCardId: "RFID-99484",
    qrCodeToken: "QR-FATIMA-NOOR-10A-99484",
    photoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: false,
    lastSafetyCheckin: "Yesterday at 01:45 PM",
    attendanceRate: 94.2,
  },
  {
    id: "stu-4",
    userId: "u-stu-4",
    fullName: "Zainab Malik",
    rollNumber: "SAF-2026-045",
    classId: "c-10a",
    className: "Grade 10 - Lily",
    parentId: "par-4",
    parentName: "Farah Malik",
    parentPhone: "+1 (555) 902-3341",
    parentEmail: "farah.malik@example.com",
    bloodGroup: "AB+",
    rfidCardId: "RFID-99485",
    qrCodeToken: "QR-ZAINAB-MALIK-10A-99485",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    isInsideCampus: true,
    lastSafetyCheckin: "Today at 07:40 AM",
    attendanceRate: 99.1,
  },
];

export const INITIAL_PARENTS: Parent[] = [
  {
    id: "par-1",
    userId: "u-par-1",
    fullName: "Tariq Ahmed",
    relationship: "Father",
    studentIds: ["stu-1"],
    studentNames: ["Sara Ahmed"],
    emergencyPhone: "+1 (555) 349-2810",
    whatsappEnabled: true,
    address: "742 Evergreen Terrace, Sector F-8",
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: "tea-1",
    userId: "u-tea-1",
    fullName: "Dr. Amina Qureshi",
    employeeId: "TEA-882",
    department: "Science & Biology",
    qualification: "Ph.D. in Cellular Biology",
    assignedClasses: ["Grade 10 - Lily", "Grade 9 - Rose"],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    rollNumber: "SAF-2026-042",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "07:45 AM",
    method: "qr_scan",
    status: "present",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-2",
    studentId: "stu-2",
    studentName: "Ayesha Khan",
    rollNumber: "SAF-2026-043",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "07:52 AM",
    method: "rfid_tap",
    status: "present",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-3",
    studentId: "stu-3",
    studentName: "Fatima Noor",
    rollNumber: "SAF-2026-044",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    method: "manual",
    status: "absent",
    parentNotifiedArrival: false,
    parentNotifiedDeparture: false,
  },
  {
    id: "att-4",
    studentId: "stu-4",
    studentName: "Zainab Malik",
    rollNumber: "SAF-2026-045",
    className: "Grade 10 - Lily",
    date: new Date().toISOString().split("T")[0],
    checkIn: "08:15 AM",
    method: "qr_scan",
    status: "late",
    parentNotifiedArrival: true,
    parentNotifiedDeparture: false,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "attendance",
    title: "Safe Arrival Confirmed",
    message: "Your daughter Sara Ahmed safely reached school at 7:45 AM via North Gate Smart QR Entry.",
    read: false,
    channel: "whatsapp",
    createdAt: "10 mins ago",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-2",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "homework",
    title: "Biology Homework Assigned",
    message: "Chapter 5: Photosynthesis & Cellular Respiration worksheet is due tomorrow by 4:00 PM.",
    read: false,
    channel: "app",
    createdAt: "1 hour ago",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-3",
    recipientId: "u-par-1",
    recipientRole: "parent",
    category: "marks",
    title: "Monthly Quiz Marks Published",
    message: "Sara scored 48/50 (Grade: A+) in Mathematics Quadratic Equations test.",
    read: true,
    channel: "email",
    createdAt: "Yesterday",
    studentName: "Sara Ahmed",
  },
  {
    id: "notif-4",
    recipientId: "u-all",
    recipientRole: "parent",
    category: "announcements",
    title: "Annual Girls STEM & Robotics Fair",
    message: "Parents are warmly invited to inspect student AI science exhibits on Thursday, Oct 15.",
    read: true,
    channel: "app",
    createdAt: "2 days ago",
  },
];

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: "em-1",
    name: "Metropolitan Women & Girls Police Station",
    type: "Police",
    phoneNumber: "+1 (555) 911-2020",
    address: "Civic Center Ave, Sector 4 (Rapid Response Post)",
    distanceKm: 0.8,
    latitude: 33.7182,
    longitude: 73.0605,
    isActive: true,
  },
  {
    id: "em-2",
    name: "St. Jude Children & Maternity Trauma Center",
    type: "Hospital",
    phoneNumber: "+1 (555) 911-4040",
    address: "12 Medical Complex Road, West Wing",
    distanceKm: 1.4,
    latitude: 33.722,
    longitude: 73.068,
    isActive: true,
  },
  {
    id: "em-3",
    name: "National Emergency & Rescue 1122 Helpline",
    type: "Helpline",
    phoneNumber: "1122",
    address: "Central Dispatch Hotline (24/7 Priority)",
    distanceKm: 2.1,
    latitude: 33.714,
    longitude: 73.052,
    isActive: true,
  },
  {
    id: "em-4",
    name: "SafeAI Campus Internal Security Desk",
    type: "Security",
    phoneNumber: "+1 (555) 723-3240",
    address: "Main Gate Guardhouse & Dispatch Booth",
    distanceKm: 0.05,
    latitude: 33.72,
    longitude: 73.06,
    isActive: true,
  },
];

export const INITIAL_HOMEWORK: HomeworkItem[] = [
  {
    id: "hw-1",
    title: "Chapter 5: Light-Dependent Reactions Diagram",
    description: "Draw and label the thylakoid membrane, ATP synthase, and electron transport chain. Explain the photolysis of water.",
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    dueDate: "Tomorrow, 4:00 PM",
    assignedBy: "Dr. Amina Qureshi",
    submissionsCount: 22,
    totalStudents: 28,
    isCompletedByStudent: true,
  },
  {
    id: "hw-2",
    title: "Quadratic Formula Word Problems",
    description: "Solve problems 14 through 22 from Page 118 of the textbook. Show the discriminant calculation for each root.",
    subject: "Mathematics & Algebra",
    className: "Grade 10 - Lily",
    dueDate: "In 2 days, 9:00 AM",
    assignedBy: "Ms. Hiba Rashid",
    submissionsCount: 16,
    totalStudents: 28,
    isCompletedByStudent: false,
  },
  {
    id: "hw-3",
    title: "Python Loops and Functions Exercise",
    description: "Implement a student grade calculator function that accepts numerical scores and returns letter grades with validation.",
    subject: "Computer Science & AI",
    className: "Grade 10 - Lily",
    dueDate: "Friday, 11:59 PM",
    assignedBy: "Engr. Noor Fatima",
    submissionsCount: 10,
    totalStudents: 28,
    isCompletedByStudent: false,
  },
];

export const INITIAL_MARKS: MarkItem[] = [
  {
    id: "m-1",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Biology & Life Sciences",
    examType: "Mid-Term Examination",
    obtainedMarks: 94.5,
    totalMarks: 100,
    grade: "A+",
    teacherRemarks: "Exemplary grasp of cell metabolism and genetic mechanisms. Active participation in laboratory sessions.",
    date: "2026-09-02",
  },
  {
    id: "m-2",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Mathematics & Algebra",
    examType: "Monthly Quiz 3",
    obtainedMarks: 48,
    totalMarks: 50,
    grade: "A+",
    teacherRemarks: "Excellent precision in factoring polynomials. Neat working.",
    date: "2026-09-08",
  },
  {
    id: "m-3",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Computer Science & AI",
    examType: "Project Practical",
    obtainedMarks: 49,
    totalMarks: 50,
    grade: "A+",
    teacherRemarks: "Outstanding project on AI ethical algorithms.",
    date: "2026-08-25",
  },
  {
    id: "m-4",
    studentId: "stu-1",
    studentName: "Sara Ahmed",
    subject: "Physics",
    examType: "Mid-Term Examination",
    obtainedMarks: 89,
    totalMarks: 100,
    grade: "A",
    teacherRemarks: "Good conceptual understanding of Newtonian dynamics; practice numerical problems on projectile motion.",
    date: "2026-09-01",
  },
];

export const INITIAL_DOCUMENTS: RAGDocument[] = [
  {
    id: "doc-1",
    title: "Grade 10 Biology - Chapter 5: Photosynthesis & Respiration",
    filename: "Biology_Chapter_5_Photosynthesis.pdf",
    fileType: "pdf",
    fileSizeKb: 3420,
    subject: "Biology & Life Sciences",
    className: "Grade 10 - Lily",
    status: "indexed",
    chunksCount: 18,
    uploadedAt: "2026-09-01",
    summary: "Comprehensive syllabus guide covering light & dark reactions, chlorophyll absorption spectra, Calvin cycle, and aerobic ATP synthesis.",
  },
  {
    id: "doc-2",
    title: "Grade 10 Mathematics - Chapter 3: Quadratic Equations & Parabolas",
    filename: "Math_Grade10_Quadratic_Equations.pdf",
    fileType: "pdf",
    fileSizeKb: 2180,
    subject: "Mathematics & Algebra",
    className: "Grade 10 - Lily",
    status: "indexed",
    chunksCount: 14,
    uploadedAt: "2026-09-03",
    summary: "Factoring quadratics, completing the square, the quadratic formula x = (-b ± √(b² - 4ac))/(2a), and nature of roots.",
  },
  {
    id: "doc-3",
    title: "SafeAI Campus Safety Protocol & Emergency Evacuation Manual",
    filename: "SafeAI_Campus_Safety_Policy_2026.pdf",
    fileType: "pdf",
    fileSizeKb: 1450,
    subject: "School Policies & Safety",
    className: "All Classes",
    status: "indexed",
    chunksCount: 10,
    uploadedAt: "2026-08-20",
    summary: "School perimeter security, visitor check-in, SOS panic trigger procedures, assembly point protocols, and medical triage steps.",
  },
];

export const INITIAL_DOCUMENT_CHUNKS: DocumentChunk[] = [
  {
    id: "chk-1",
    documentId: "doc-1",
    chunkIndex: 1,
    page: 42,
    content: "Photosynthesis is the biological process by which green plants, algae, and cyanobacteria convert light energy, primarily from the Sun, into chemical energy stored in glucose. The overall balanced chemical equation is: 6CO2 + 6H2O + light energy -> C6H12O6 + 6O2. It occurs inside specialized cellular organelles called chloroplasts, which contain light-absorbing pigments termed chlorophyll.",
  },
  {
    id: "chk-2",
    documentId: "doc-1",
    chunkIndex: 2,
    page: 44,
    content: "The photosynthesis process occurs in two primary stages: 1) The Light-Dependent Reactions, which take place across the thylakoid membranes where light energy splits water molecules (photolysis) producing oxygen, ATP, and NADPH. 2) The Light-Independent Reactions (Calvin Cycle), which occur within the stroma and utilize ATP and NADPH to fix atmospheric carbon dioxide into high-energy sugars such as G3P and glucose.",
  },
  {
    id: "chk-3",
    documentId: "doc-1",
    chunkIndex: 3,
    page: 48,
    content: "Cellular respiration is the complementary metabolic pathway where cells break down glucose in the presence of oxygen to release usable chemical energy in the form of Adenosine Triphosphate (ATP). The equation is C6H12O6 + 6O2 -> 6CO2 + 6H2O + 36-38 ATP. The three key phases are Glycolysis (in cytoplasm), the Krebs Cycle (in mitochondrial matrix), and the Electron Transport Chain (inner mitochondrial cristae).",
  },
  {
    id: "chk-4",
    documentId: "doc-2",
    chunkIndex: 1,
    page: 72,
    content: "A quadratic equation is a second-degree polynomial equation of the standard form ax² + bx + c = 0, where a, b, and c are real constants and a ≠ 0. The solutions or roots can be derived using the quadratic formula: x = (-b ± √(b² - 4ac)) / (2a). The term Δ = b² - 4ac is called the discriminant. If Δ > 0, the equation has two distinct real roots; if Δ = 0, exactly one real root (repeated); if Δ < 0, two conjugate complex roots.",
  },
  {
    id: "chk-5",
    documentId: "doc-2",
    chunkIndex: 2,
    page: 78,
    content: "Methods for solving quadratic equations include: 1) Factoring by grouping or middle-term splitting. 2) Completing the square method. 3) Applying the quadratic formula. In real-world applications, parabolas model projectile motion, architectural arches, satellite dishes, and revenue optimization curves.",
  },
  {
    id: "chk-6",
    documentId: "doc-3",
    chunkIndex: 1,
    page: 5,
    content: "SafeAI Campus Emergency & SOS Protocol: If an emergency, security concern, or health anomaly arises, students can press the red SOS Panic Button in the SafeAI Student App or smart safety badges. Activation automatically: 1) Dispatches instant SMS and push alerts with live GPS coordinates to verified parents. 2) Rings the Central Security Control Room. 3) Alerts designated female campus safety officers and the nearest rapid response police precinct.",
  },
  {
    id: "chk-7",
    documentId: "doc-3",
    chunkIndex: 2,
    page: 8,
    content: "Geofencing & Campus Gate Protocols: The school campus boundary is protected by an active virtual geofence. When a student passes the biometric or RFID entry gate, parents immediately receive automated notification: 'Your daughter [Name] safely reached school at [Time]'. If an unscheduled exit occurs before dismissal hours, high-priority safety alerts are generated to guardians and security chiefs.",
  },
];

export const INITIAL_MCQS: MCQQuestion[] = [
  {
    id: "mcq-1",
    question: "Where do the light-dependent reactions of photosynthesis take place inside a plant cell?",
    options: {
      A: "Stroma of the chloroplast",
      B: "Thylakoid membranes",
      C: "Outer mitochondrial membrane",
      D: "Cytoplasm",
    },
    correctAnswer: "B",
    explanation: "According to Biology Chapter 5 (p. 44), light-dependent reactions occur across the thylakoid membranes, where chlorophyll pigments absorb photons and drive photolysis of water.",
    difficulty: "Easy",
  },
  {
    id: "mcq-2",
    question: "What is the primary function of the Calvin Cycle during photosynthesis?",
    options: {
      A: "To split water molecules into oxygen and protons",
      B: "To synthesize ATP using proton gradients",
      C: "To fix atmospheric CO2 into high-energy sugars using ATP and NADPH",
      D: "To absorb blue and red wavelengths of light",
    },
    correctAnswer: "C",
    explanation: "The Calvin Cycle (light-independent phase in the stroma) uses chemical energy from ATP and reducing power from NADPH to fix CO2 into glucose (p. 44).",
    difficulty: "Medium",
  },
  {
    id: "mcq-3",
    question: "For a quadratic equation ax² + bx + c = 0, what does a discriminant value of Δ = b² - 4ac < 0 indicate?",
    options: {
      A: "Two distinct real roots",
      B: "One repeated real root",
      C: "Two conjugate complex roots (no real roots)",
      D: "A linear equation",
    },
    correctAnswer: "C",
    explanation: "When Δ < 0, the square root √(Δ) yields an imaginary quantity, indicating two complex conjugate roots (Math Chapter 3, p. 72).",
    difficulty: "Medium",
  },
  {
    id: "mcq-4",
    question: "What immediate action is automatically triggered when a student activates the SafeAI SOS Emergency feature?",
    options: {
      A: "The phone resets all stored passwords",
      B: "Instant push & SMS alerts with live GPS are sent to parents, security, and nearest rapid response precinct",
      C: "The student's attendance is marked absent",
      D: "The exam timer is restarted",
    },
    correctAnswer: "B",
    explanation: "The Campus Safety Manual Section 2 specifies that SOS sends real-time coordinates, notifies parents instantly, and alerts campus security and emergency response teams.",
    difficulty: "Easy",
  },
  {
    id: "mcq-5",
    question: "How many net ATP molecules are typically produced per glucose molecule during aerobic cellular respiration?",
    options: {
      A: "2 ATP",
      B: "12-14 ATP",
      C: "36-38 ATP",
      D: "100 ATP",
    },
    correctAnswer: "C",
    explanation: "Aerobic cellular respiration completes glycolysis, the Krebs cycle, and electron transport chain phosphorylation, generating 36 to 38 ATP per glucose molecule (Biology p. 48).",
    difficulty: "Hard",
  },
];

export const INITIAL_FLASHCARDS: Flashcard[] = [
  {
    id: "fc-1",
    topic: "Photosynthesis",
    subject: "Biology",
    question: "What is Photolysis of Water?",
    answer: "The photochemical splitting of H2O into electrons, protons (H+), and molecular oxygen (O2) in photosystem II during light-dependent reactions.",
  },
  {
    id: "fc-2",
    topic: "Cellular Respiration",
    subject: "Biology",
    question: "Where does the Krebs Cycle occur?",
    answer: "In the mitochondrial matrix of eukaryotic cells.",
  },
  {
    id: "fc-3",
    topic: "Quadratic Equations",
    subject: "Mathematics",
    question: "What is the Quadratic Formula?",
    answer: "x = (-b ± √(b² - 4ac)) / (2a)",
  },
  {
    id: "fc-4",
    topic: "Safety & Geofencing",
    subject: "Campus Safety",
    question: "What triggers an automated parent departure notification?",
    answer: "When a student scans their QR badge or taps their RFID card at the departure turnstile.",
  },
];
